### ISSUE TITLE
Video players other then VLC?

### ISSUE THREAD

**Issue by kurokin** [s1mpl3x/skadi#1]
Is there any reason why this is locked to VLC?

**Comment by s1mpl3x** [comment]
I'm using the  `--qt-minimal-view` flag (https://github.com/s1mpl3x/skadi/blob/master/src/main/java/eu/over9000/skadi/handler/StreamHandler.java#L108), apart from that any player supported by livestreamer should work

**Comment by kurokin** [comment]
Will you add a settings option to chose a specified player?

**Comment by s1mpl3x** [comment]
yea i'll see how i can do that nicely, one option would be to rely on the livestreamer config to contain the videoplayer info.. which would add another error source/ setup step. Or videoplayer/arguments settings instead of the vlc setting
