### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by laurencee** [s1mpl3x/skadi#20]
My skadi has 88 channels saved and on start up after the initial refresh has completed the app sits around 350MB. 
After leaving it run for most of the day it climbs towards 1GB.

This seems like quite a lot of memory to me for what the app is providing. 
Do you think you could take a look into what's taking up most of the memory?

Additional Info:
Win 10 x64, Skadi configuration is in table view on the dark theme.

**Comment by s1mpl3x** [comment]
Yes the mem usage is absolutely abysmal. That can be credited on Java for a huge part but apart from that there is currently 1 thing leaking memory i know of is the viewer history as it isn't dropping any old data and therefore keeps growing... I'll look into it if and maybe add an config value for a limit of history time and will check if something else is leaking

**Comment by s1mpl3x** [comment]
ok so i checked and the viewer data is negligible. From the memory the jvm is reserving, which is ~1.5gb on my pc, skadi never used more than 300mb and was mostly around 150mb. So you might want to start the jvm with -Xmx=512m or something which should be enough

**Comment by laurencee** [comment]
Hmm I see, primarily due to this I've written my own version of this app in .NET 4.6 (testing out new language features). 
I have a couple less features right now and some I wont bother implementing (like the info button). 

It tends to be between 50-80MB with the same list of channels.

I'll reference your app in my readme (if you don't mind) when i put it on github since it heavily influenced the layout and feature set. Also since .NET is not cross platform (at least for WPF), it's only for the windows users out there while you can use your app on most platforms.

EDIT: I pushed what I have so far to github: https://github.com/laurencee/Livestream.Monitor

**Comment by s1mpl3x** [comment]
Yea sure ill check it out :)
Closing this as there isn't really much i can do
