### ISSUE TITLE
Explain purpose of Version Check.

### ISSUE THREAD

**Issue by piddubnyi** [s1mpl3x/skadi#32]
I'm using skadi for some time now. Today I tried it in new pc, and it gave error regarding Java version.
It was 1.8.0_20 instead of 1.8.0_60.
After I pulled code and fixed JavaVersionUtil.REQUIRED_VERSION variable, the program was running fine.
Is there a particular reason for that particular version check ?

**Comment by s1mpl3x** [comment]
https://bugs.openjdk.java.net/browse/JDK-8094778 this bug was fixed in 1.8.0_60 that in certain cases caused the rendering thread to crash if the online-only filter was used
