### ISSUE TITLE
problem with quality choice for subscriber's only quality

### ISSUE THREAD

**Issue by jidea** [s1mpl3x/skadi#9]
on twitch.tv/OGamingSC2, skadi shows only 'worst' quality choice (and best by default).
the answer to a livestreamer request is:
"[plugin.twitch][warning] The quality 'source' is not available since it requires a subscription.
Available streams: audio, high (best), low, medium, mobile (worst)"

**Comment by s1mpl3x** [comment]
the quality display thing might be a bit harder to do, but subscription content can be played by livestreamer, so skadi should not be involved for the playback part:

http://docs.livestreamer.io/cli.html#authenticating-with-twitch

I guess to display subscription-qualities i would have to do the whole oauth stuff in skadi or fall back to parse the livestreamer output...
